language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER=weak

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source
  - php app/console doctrine:phpcr:init:dbal -e=test

script: phpunit -c app

notifications:
  slack: liip:3QOs1QKt3aCFxpJvRzpJCbVZ
