imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig', 'php'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    session:
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ LiipHelloBundle ]
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        path:     %database_path%
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

jms_security_extra:
    secure_all_services: false

jms_serializer:
    handlers:
        object_based: true

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Liip\HelloBundle\Entity\User

fos_facebook:
    file:   %kernel.root_dir%/../vendor/facebook/src/base_facebook.php
    alias:  facebook
    app_id: 200207463333974
    secret: a7d05283b77147f065098358ddb5674c
    cookie: true
    permissions: [email, user_birthday, user_location]

fos_rest:
    view:
#        default_engine: php
        view_response_listener: force
        force_redirects:
          html: true
#          xml: true
        formats:
            json: true
            xml: true
            rss: false
        templating_formats:
            html: true
        mime_types:
            json: ['application/json', 'application/x-json', 'application/vnd.example-com.foo+json']
            rss: 'application/rss+xml'
            jpg: 'image/jpeg'
            png: 'image/png'
    body_listener: true
    query_fetcher_listener: force
    format_listener:
        default_priorities:
            - html
            - json
            - xml
            - rss
            - "*/*"
            # never reached due to "*/*"
            - ding
        # the subsequent line overrides the following line, so the default is NULL
        fallback_format: json
        fallback_format: ~
        prefer_extension: true
    routing_loader:
        default_format: ~
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    service:
        view_handler: liip_hello.view_handler
    serializer:
#        version: 1.0
#        groups: [data]

doctrine_phpcr:
    session:
        backend:
            type: doctrinedbal
            connection: database_connection
#            type: jackrabbit
#            url: http://localhost:8080/server/
#            disable_stream_wrapper: true
        workspace: default
        username: admin
        password: admin
        options:
            'jackalope.fetch_depth': 1
    odm:
        auto_generate_proxy_classes: %kernel.debug%
        mappings:
            LiipHelloBundle: true

liip_hello:
    facebook: true

liip_vie:
    filter: true
    phpcr_odm: true
    map:
        '<article>': 'Liip\HelloBundle\Document\Article'

sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }
    request: { converters: true }

liip_container_wrapper:
    disable_optimization: false

liip_cache_control:
#    rules:
#        - { path: /, controls: { public: true, max_age: 15, s_maxage: 30, last_modified: "-1 hour" } }
#    varnish:
#        domain: http://symfony-standard.lo
#        ips: 10.0.0.10, 10.0.0.11 # comma separated list of ips, or an array of ips
#        port: 80  # port varnish is listening on for incoming web connections
    authorization_listener: true
    flash_message_listener: false

liip_hyphenator:
    language: de_DE
    hyphen: '&shy;'

liip_theme:
    themes: ['desktop', 'tablet', 'phone']
    active_theme: 'desktop'
    cookie:
        name: 'device'
    autodetect_theme: true

liip_imagine:
    formats: [jpg, png]
    filter_sets:
        my_thumb:
            quality: 50
            filters:
                thumbnail: { size: [120, 90], mode: outbound }

        my_thumb_resize:
            quality: 50
            cache: false
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
                relative_resize: { heighten: 78 }

liip_doctrine_cache:
    namespaces:
        foo:
            namespace: ding
            type: apc
