imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    translator: { fallback: en }
    secret:        %secret%
    charset:       UTF-8
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'
    csrf_protection:
        enabled: true
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enabled: true, annotations: true }
    templating:    { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        lifetime:       3600
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        path:     %database_path%
        driver:   %database_driver%
        host:     %database_host%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

#jms_security_extra:
#    secure_controllers:  true
#    secure_all_services: false

fos_user:
    db_driver: orm
    firewall_name: main
    class:
        model:
            user: Liip\HelloBundle\Entity\User

fos_facebook:
    file:   %kernel.root_dir%/../vendor/facebook/src/facebook.php
    alias:  facebook
    app_id: 200207463333974
    secret: a7d05283b77147f065098358ddb5674c
    cookie: true
    permissions: [email, user_birthday, user_location]

fos_rest:
    frameworkextra_bundle: true
#    serializer_bundle: true
    body_listener: true
    format_listener:
        default_priorities:
            - html
            - json
            - xml
            - "*/*"
            - ding
        default_format: json
        default_format: ~
    exception:
        codes:
            'Symfony\Component\Routing\Matcher\Exception\NotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Matcher\Exception\NotFoundException': true
    normalizers:
        'Liip\HelloBundle\Document\Article': 'fos_rest.get_set_method_normalizer'

doctrine_phpcr:
    backend:
        url: http://localhost:8080/server/
        workspace: default
        user: admin
        pass: admin
#        transport: doctrinedbal

liip_hello:
    facebook: true

sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }

liip_container_wrapper:
    disable_optimization: false

liip_cache_control:
#    rules:
#        - { path: /, controls: { public: true, max_age: 15, s_maxage: 30, last_modified: "-1 hour" } }
#      purger:
#          domain: http://symfony-standard.lo
#          varnishes: 10.0.0.10, 10.0.0.11 # comma separated list of ips, or an array of ips
#          port: 80  # port varnish is listening on for incoming web connections
