parameters:
  database_driver:   pdo_sqlite
  database_host:     localhost
  database_port:     ~
  database_name:     symfony
  database_user:     root
  database_password: ~
  database_path:     %kernel.root_dir%/app.sqlite

  mailer_transport:  smtp
  mailer_host:       localhost
  mailer_user:       ~
  mailer_password:   ~

  locale:            en
  secret:            ThisTokenIsNotSoSecretChangeIt

  symfony_cmf_core.mainmenu_basepath: /cms/navigation/main
  symfony_cmf_core.routing_basepath: /cms/routes
  symfony_cmf_content.static_basepath: /cms
