hello:
    resource: "@LiipHelloBundle/Resources/config/routing.yml"

security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix:   /liip

profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix:   /liip/profile

registration:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix:   /liip/register

_imagine:
    resource: .
    type:     imagine

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

theme:
    resource: "@LiipThemeBundle/Resources/config/routing.xml"
    prefix:   /liip/theme

monitor:
    resource: "@LiipMonitorBundle/Resources/config/routing.yml"
    prefix:   /liip