hello:
    resource: "@LiipHelloBundle/Resources/config/routing.yml"

security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"

registration:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"

vie:
    resource: "@LiipVieBundle/Resources/config/routing/phpcr_odm.xml"

_imagine:
    resource: .
    type:     imagine

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
