hello:
    resource: "@LiipHelloBundle/Resources/config/routing.yml"

security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix:   /liip

profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix:   /liip/profile

registration:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix:   /liip/register

vie:
    resource: "@LiipVieBundle/Resources/config/routing/phpcr_odm.xml"

_imagine:
    resource: .
    type:     imagine

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

theme:
    resource: "@LiipThemeBundle/Resources/config/routing.xml"
    prefix:   /liip/theme
