_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml

# demo routes (to be removed)
_acme_demo:
    resource: "@AcmeDemoBundle/Resources/config/routing.yml"

hello:
    resource: "@LiipHelloBundle/Resources/config/routing.yml"

security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix:   /liip

profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix:   /liip/profile

registration:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix:   /liip/register

_imagine:
    resource: .
    type:     imagine

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

theme:
    resource: "@LiipThemeBundle/Resources/config/routing.xml"
    prefix:   /liip/theme

monitor:
    resource: "@LiipMonitorBundle/Resources/config/routing.yml"
    prefix:   /liip

fos_facebook_channel:
    pattern:  /channel.html
    defaults: { _controller: "FOSFacebookBundle:Facebook:channel" }