security:
    factories:
        - "%kernel.root_dir%/../vendor/bundles/FOS/FacebookBundle/Resources/config/security_factories.xml"

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_facebook:
            id: liip_hello.facebook.user
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        profiler:
            pattern:  ^/_profiler
            security: false

        wdt:
            pattern:  ^/_wdt
            security: false

        main:
            pattern:   /.*
            form_login:
                login_path: /login
                check_path: /login-check
                provider: fos_userbundle

            fos_facebook:
                login_path: /liip/facebook
                check_path: /liip/facebook-check
                default_target_path: /liip/facebook
                provider: fos_facebook

            anonymous: true
            logout:
                path: /liip/facebook-logout
                target: /liip/facebook

    access_control:
        - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
