security:
#    factories:
#        - "%kernel.root_dir%/../vendor/bundles/FOS/FacebookBundle/Resources/config/security_factories.xml"

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
#        fos_facebook:
#            id: liip_hello.facebook.user
        fos_userbundle:
            id: fos_user.user_manager

        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:   /.*
            form_login:
                login_path: /login
                check_path: /login-check
                provider: fos_userbundle

#            fos_facebook:
#                login_path: /liip/facebook
#                check_path: /liip/facebook-check
#                default_target_path: /liip/facebook
#                provider: fos_facebook

            anonymous: true
            logout:
                path: /liip/facebook-logout
                target: /liip/facebook

    access_control:
        - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
